# .readthedocs.yaml
# Read the Docs configuration for MkDocs

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
python:
  install:
    - requirements: docs_src/requirements.txt
    - method: pip
      path: .

mkdocs:
  configuration: mkdocs.yml
