site_name: SussyOS Docs
site_url: https://sussyos.github.io/docs/
site_description: Official SussyOS Documentation
repo_url: https://github.com/sussyos/sussyos.github.io

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand        # collapsible sections expand by default
    - navigation.sections      # group by folder structure
    - navigation.top           # keeps top-level nav always visible

nav:
  - Home: index.md

# Source directory for Markdown files
docs_dir: docs_src

# Output directory for generated HTML (served at /docs/)
site_dir: docs

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
