site_name: SussyOS Docs
site_url: https://sussyos.github.io/docs/
site_description: Official SussyOS Documentation
repo_url: https://github.com/sussyos/sussyos.github.io

theme:
  name: material
  palette:
    primary: teal
    accent: amber
  font:
    text: "Inter"
    code: "Fira Code"
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top

nav:
  - Home: index.md

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
