name: Build MkDocs Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch full history so we can pull/rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install MkDocs
        run: |
          pip install mkdocs

      - name: Build MkDocs site into /docs
        run: |
          mkdocs build

      - name: Commit and push built docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Auto-build MkDocs documentation [skip ci]" || echo "No changes to commit"
          
          # --- Fix for push rejection ---
          git pull --rebase origin main || true
          git push --force-with-lease origin main
